#### ¿Qué es Pandas?
- **Definición**: Pandas es una biblioteca de software (paquete) que agrega funcionalidades a Python para la manipulación y el análisis de datos.
- **Usos Principales**: Se utiliza principalmente para la limpieza de datos, análisis exploratorio, y visualización de datos estadísticos.

#### Importancia de Pandas en Data Science
- **Facilita el Manejo de Datos**: Pandas simplifica el manejo de datos, para enfocarnos en el análisis.
- **Adaptado a Diferentes Fuentes de Datos**: Puede trabajar con una variedad de formatos de datos, como CSV, Excel, bases de datos SQL, entre otros.
- **Esencial para Análisis de Datos**: Es una herramienta clave en cualquier flujo de trabajo de Data Science para la preparación y exploración de datos.

#### Importación de Pandas
- **¿Dónde está Pandas?**: A pesar de que Pandas no forma parte de la estructura original de Python, es una librería adicional que Anaconda instaló en nuestro ordenador al mismo momento que instaló Python.
- **Importar Pandas**: A pesar de que ya está instalado, debes importarlo a tu entorno de trabajo (cuaderno) para utilizarlo en el código de python.
- **Comando de importación**: ```import pandas as pd```

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('..\data\Precipitaciones.csv')

In [ ]:
df

In [5]:
df.shape

(52, 14)

In [6]:
df.head()

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6
3,ALMERIA,56.3,5.2,35.8,43.1,38.8,16.9,10.2,1.9,17.4,27.3,32.6,3.2,288.7
4,ARABA,96.8,79.9,38.0,52.0,37.7,107.8,8.5,17.7,63.3,38.5,212.2,197.3,949.7

In [4]:
df.describe()

,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,92.996154,78.632692,26.684615,64.500000,38.305769,54.182692,11.840385,17.178846,62.246154,54.373077,82.494231,76.192308,659.626923
std,57.127171,67.454280,31.473913,21.421942,29.079576,36.821635,13.256390,13.939496,28.581205,36.619785,91.689789,80.409042,352.905548
min,26.800000,2.300000,3.300000,3.500000,0.700000,1.100000,0.000000,0.000000,0.900000,1.000000,7.100000,1.800000,108.200000
25%,53.825000,32.825000,9.125000,53.950000,18.875000,26.325000,1.600000,4.850000,46.000000,29.825000,32.375000,22.075000,455.925000
50%,73.950000,62.600000,17.200000,62.700000,35.650000,50.400000,6.150000,16.500000,62.300000,46.550000,46.950000,47.950000,548.550000
75%,97.300000,102.550000,35.425000,77.625000,48.750000,78.025000,17.875000,26.550000,81.625000,74.500000,102.725000,107.000000,665.150000
max,261.900000,335.700000,209.800000,128.400000,149.500000,145.000000,46.800000,57.000000,122.800000,175.700000,384.600000,314.700000,1575.400000