In [1]:
import pandas  as pd

In [9]:
ruta_excel=r'D:\Users\jvelasqu\Desktop\PROYECTOS\curso de python\Parte 7\data\Compras_desde_ads.xlsx'
ruta_xml=r'D:\Users\jvelasqu\Desktop\PROYECTOS\curso de python\Parte 7\data\Valores+de+acciones.xml'

In [7]:
df1=pd.read_excel(ruta_excel)
df1.head()

   Id_usuario     Genero  Edad  Salario_estimado  Comprado
0    15624510  Masculino    19             19000         0
1    15810944  Masculino    35             20000         0
2    15668575   Femenino    26             43000         0
3    15603246   Femenino    27             57000         0
4    15804002  Masculino    19             76000         0

In [20]:
df2=pd.read_xml(ruta_xml)
df2.head()

         date closingValue
0  01-05-2023        25,05
1  02-05-2023        24,45
2  03-05-2023        24,45
3  04-05-2023        23,98
4  05-05-2023        24,56

OperationalError: could not translate host name "mgq.vps.webdock.cloud" to address: Name or service not known